import type {
  EverydayDiscoveryImageCredit,
  EverydayDiscoveryItem,
  EverydayDiscoveryScene,
} from "./everyday-discovery-data";

const IMAGE_ROOT = "/everyday-discovery";
const AUDIO_ROOT = "/everyday-discovery-audio";

export const MARKET_WEATHER_IMAGE_CREDITS = {
  trolley: { author: "safaritravelplus", license: "CC0 1.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Shopping_Cart_Supermarket.jpg", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", adaptation: "cropped and resized" },
  basket: { author: "Lars Plougmann", license: "CC BY-SA 2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Wheelie_shopping_basket.jpg", licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/", adaptation: "resized over a blurred crop" },
  aisle: { author: "Tessa Bury", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Grocery_Store_Aisle,_vermont.jpg", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", adaptation: "cropped and resized" },
  cashier: { author: "Manzanita2203", license: "CC BY-SA 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cajera_supermercado.jpg", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", adaptation: "resized over a blurred crop" },
  receipt: { author: "Tessa Bury", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cashier_handing_receipt.jpg", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", adaptation: "cropped and resized" },
  barcode: { author: "Mike1024", license: "Public domain", sourceUrl: "https://commons.wikimedia.org/wiki/File:GS1-128_product_barcode.jpg", licenseUrl: "https://commons.wikimedia.org/wiki/Template:PD-self", adaptation: "cropped and resized" },
  groceries: { author: "Bill Branson / National Cancer Institute", license: "Public domain (US NIH)", sourceUrl: "https://commons.wikimedia.org/wiki/File:Grocery_bag_of_healthy_foods.jpg", licenseUrl: "https://commons.wikimedia.org/wiki/Template:PD-USGov-HHS-NIH", adaptation: "cropped and resized" },
  checkout: { author: "維基小霸王", license: "CC BY-SA 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cashier_counters.jpg", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", adaptation: "cropped and resized" },
  sunny: { author: "Mukesh M / OrbitingWeb.com", license: "CC BY 3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:A_Sunny_Day_(162885303).jpeg", licenseUrl: "https://creativecommons.org/licenses/by/3.0/", adaptation: "cropped and resized" },
  cloudy: { author: "StockyPics", license: "CC0 1.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Cloudy_sky_(22423720301).jpg", licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/", adaptation: "cropped and resized" },
  windy: { author: "R MORGAN (RobSCM)", license: "CC BY 3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Trees_Windswept.JPG", licenseUrl: "https://creativecommons.org/licenses/by/3.0/", adaptation: "cropped and resized" },
  rainy: { author: "rommy ghaly", license: "CC BY 2.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Rain_on_Water_Street.jpg", licenseUrl: "https://creativecommons.org/licenses/by/2.0/", adaptation: "cropped and resized" },
  thunderstorm: { author: "Rollingskyphoto", license: "CC BY 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Lightning_with_Shelf_Cloud.jpg", licenseUrl: "https://creativecommons.org/licenses/by/4.0/", adaptation: "cropped and resized" },
  lightning: { author: "jacobtohahn", license: "CC BY-SA 4.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Lightning_at_Night.jpg", licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/", adaptation: "cropped and resized" },
  temperature: { author: "M. Minderhoud", license: "CC BY-SA 3.0", sourceUrl: "https://commons.wikimedia.org/wiki/File:Thermometer.jpg", licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/", adaptation: "resized over a blurred crop" },
  forecast: { author: "National Weather Service", license: "Public domain (US NOAA)", sourceUrl: "https://commons.wikimedia.org/wiki/File:Weather_map_example.png", licenseUrl: "https://commons.wikimedia.org/wiki/Template:PD-USGov-NOAA", adaptation: "resized over a blurred crop and converted to JPEG" },
} as const satisfies Partial<Record<EverydayDiscoveryItem["id"], EverydayDiscoveryImageCredit>>;

function item(
  definition: Omit<
    EverydayDiscoveryItem,
    "imageSrc" | "wordAudioSrc" | "coachAudioSrc" | "descriptionAudioSrc" | "imageCredit" | "coachScript"
  > & { coachScript?: string },
): EverydayDiscoveryItem {
  const root = `${AUDIO_ROOT}/${definition.sceneId}/${definition.id}`;
  const chunkCues = definition.chunks.map((chunk) => chunk.cue).join(". ");
  return {
    ...definition,
    imageSrc: `${IMAGE_ROOT}/${definition.sceneId}/${definition.id}.jpg`,
    imageCredit: MARKET_WEATHER_IMAGE_CREDITS[definition.id as keyof typeof MARKET_WEATHER_IMAGE_CREDITS],
    coachScript: definition.coachScript
      ?? `Listen, then say each part: ${chunkCues}. Now blend it: ${definition.pronunciation}. ${definition.word}.`,
    wordAudioSrc: `${root}/whole.mp3`,
    coachAudioSrc: `${root}/coach.mp3`,
    descriptionAudioSrc: `${root}/description.mp3`,
  };
}

export const MARKET_WEATHER_SCENES: readonly EverydayDiscoveryScene[] = [
  {
    id: "supermarket",
    title: "Supermarket Mission",
    titleZh: "超市小任务",
    icon: "🛒",
    accent: "#d97745",
    eyebrow: "Choose · Count · Check out",
    description: "Follow a shopping trip from trolley to checkout and learn the useful words along the way.",
    descriptionZh: "从推购物车到结账，沿着一次购物旅程学习实用英语。",
    itemIds: ["trolley", "basket", "aisle", "cashier", "receipt", "barcode", "groceries", "checkout"],
    challenge: {
      prompt: "Which word means the path between supermarket shelves?",
      promptZh: "哪个词表示超市货架之间的通道？",
      options: [
        { id: "aisle", label: "Aisle", labelZh: "通道", icon: "🛒" },
        { id: "receipt", label: "Receipt", labelZh: "收据", icon: "🧾" },
        { id: "trolley", label: "Trolley", labelZh: "购物车", icon: "🛒" },
      ],
      answerId: "aisle",
      success: "Yes! We walk down an aisle to find groceries.",
      successZh: "答对了！我们沿着 aisle 寻找商品。",
    },
  },
  {
    id: "weather",
    title: "Weather Watch",
    titleZh: "天气观察站",
    icon: "🌦️",
    accent: "#4b87b9",
    eyebrow: "Look · Feel · Predict",
    description: "Look at the sky, feel the air and learn words that help us talk about changing weather.",
    descriptionZh: "观察天空、感受空气，学习描述天气变化的词。",
    itemIds: ["sunny", "cloudy", "windy", "rainy", "thunderstorm", "lightning", "temperature", "forecast"],
    challenge: {
      prompt: "Which word tells us what the weather may be like later?",
      promptZh: "哪个词告诉我们之后的天气可能怎样？",
      options: [
        { id: "forecast", label: "Forecast", labelZh: "天气预报", icon: "📰" },
        { id: "barcode", label: "Barcode", labelZh: "条形码", icon: "🏷️" },
        { id: "basket", label: "Basket", labelZh: "篮子", icon: "🧺" },
      ],
      answerId: "forecast",
      success: "Exactly! A forecast is a careful prediction about the weather.",
      successZh: "没错！forecast 是对天气的科学预测。",
    },
  },
];

export const MARKET_WEATHER_ITEMS: readonly EverydayDiscoveryItem[] = [
  item({
    id: "trolley", sceneId: "supermarket", word: "trolley", wordZh: "购物车",
    chunks: [{ id: "trol", text: "trol", cue: "TRAH", stressed: true }, { id: "ley", text: "ley", cue: "lee", stressed: false }],
    pronunciation: "TRAH · lee", ipa: "/ˈtrɑːli/",
    description: ["A trolley has wheels and a large basket.", "We push the trolley through the supermarket.", "It carries our shopping until we reach checkout."],
    descriptionZh: ["购物车有轮子和一个大篮子。", "我们推着购物车穿过超市。", "它装着我们的商品，直到到达结账处。"],
    descriptionKeywords: [{ word: "wheels", zh: "轮子" }, { word: "supermarket", zh: "超市" }, { word: "checkout", zh: "结账处" }],
    discovery: "In Singapore and British English, trolley is common; in American English, people often say shopping cart.",
    discoveryZh: "新加坡和英国常说 trolley；美国人常说 shopping cart。",
    soundTip: "Start with a strong TRAH, then finish lightly with lee.", soundTipZh: "先有力地读 TRAH，再轻轻接 lee。",
    factSourceUrl: "https://dictionary.cambridge.org/dictionary/english/trolley",
  }),
  item({
    id: "basket", sceneId: "supermarket", word: "basket", wordZh: "购物篮",
    chunks: [{ id: "bas", text: "bas", cue: "BAS", stressed: true }, { id: "ket", text: "ket", cue: "kit", stressed: false }],
    pronunciation: "BAS · kit", ipa: "/ˈbæskɪt/",
    description: ["A basket is smaller than a trolley.", "We carry it by its handles.", "It is useful when we need only a few groceries."],
    descriptionZh: ["购物篮比购物车小。", "我们提着它的把手。", "只需买少量食品杂货时，它很方便。"],
    descriptionKeywords: [{ word: "trolley", zh: "购物车" }, { word: "handles", zh: "把手" }, { word: "groceries", zh: "食品杂货" }],
    discovery: "A basket is handy for a short shopping list because we carry it instead of pushing it.",
    discoveryZh: "购物清单很短时，用手提的篮子很方便。",
    soundTip: "Use the short a in cat: BAS-kit.", soundTipZh: "BAS 里是 cat 中的短 a 音。",
    factSourceUrl: "https://dictionary.cambridge.org/dictionary/english/shopping-basket",
  }),
  item({
    id: "aisle", sceneId: "supermarket", word: "aisle", wordZh: "走道 / 货架通道",
    chunks: [{ id: "aisle", text: "aisle", cue: "EYLE", stressed: true }],
    pronunciation: "EYLE", ipa: "/aɪl/",
    description: ["An aisle is a path between shelves.", "We walk down an aisle to find food.", "Signs help us choose the right aisle."],
    descriptionZh: ["aisle 是货架之间的通道。", "我们沿着通道找食物。", "指示牌帮我们选对通道。"],
    descriptionKeywords: [{ word: "shelves", zh: "货架" }, { word: "walk", zh: "行走" }, { word: "signs", zh: "指示牌" }],
    discovery: "The s in aisle is silent, so aisle sounds like I'll.", discoveryZh: "aisle 里的 s 不发音，它听起来和 I'll 一样。",
    soundTip: "Say EYLE in one beat; it rhymes with smile.", soundTipZh: "一拍读完 EYLE，它和 smile 押韵。",
    factSourceUrl: "https://www.merriam-webster.com/dictionary/aisle",
  }),
  item({
    id: "cashier", sceneId: "supermarket", word: "cashier", wordZh: "收银员",
    chunks: [{ id: "cash", text: "cash", cue: "kash", stressed: false }, { id: "ier", text: "ier", cue: "SHEER", stressed: true }],
    pronunciation: "kash · SHEER", ipa: "/kæˈʃɪr/",
    description: ["A cashier helps customers pay for shopping.", "The cashier scans each barcode.", "Then the cashier gives us a receipt."],
    descriptionZh: ["收银员帮助顾客付款。", "收银员扫描每个条形码。", "然后收银员把收据给我们。"],
    descriptionKeywords: [{ word: "customers", zh: "顾客" }, { word: "barcode", zh: "条形码" }, { word: "receipt", zh: "收据" }],
    discovery: "A cashier may take payment, scan items and answer simple questions.", discoveryZh: "收银员会收款、扫描商品，也会回答简单问题。",
    soundTip: "Make the second part strong: kash-SHEER.", soundTipZh: "第二部分要重读：kash-SHEER。",
    factSourceUrl: "https://www.merriam-webster.com/dictionary/cashier",
  }),
  item({
    id: "receipt", sceneId: "supermarket", word: "receipt", wordZh: "收据",
    chunks: [{ id: "re", text: "re", cue: "rih", stressed: false }, { id: "ceipt", text: "ceipt", cue: "SEET", stressed: true }],
    pronunciation: "rih · SEET", ipa: "/rɪˈsiːt/",
    description: ["A receipt is a record of what we bought.", "It shows each item and its price.", "We receive the receipt after checkout."],
    descriptionZh: ["收据是我们所购商品的记录。", "它列出每件商品和价格。", "结账后我们会收到收据。"],
    descriptionKeywords: [{ word: "record", zh: "记录" }, { word: "price", zh: "价格" }, { word: "checkout", zh: "结账" }],
    discovery: "The p in receipt is silent, but we still write it.", discoveryZh: "receipt 里的 p 不发音，但拼写时不能丢。",
    soundTip: "Stress SEET and keep the p silent.", soundTipZh: "重读 SEET，p 不发音。",
    factSourceUrl: "https://www.merriam-webster.com/dictionary/receipt",
  }),
  item({
    id: "barcode", sceneId: "supermarket", word: "barcode", wordZh: "条形码",
    chunks: [{ id: "bar", text: "bar", cue: "BAR", stressed: true }, { id: "code", text: "code", cue: "kohd", stressed: false }],
    pronunciation: "BAR · kohd", ipa: "/ˈbɑrkoʊd/",
    description: ["A barcode is a pattern of black lines and spaces.", "A scanner reads the barcode.", "It helps the shop find the product and price."],
    descriptionZh: ["条形码是由黑线和空白组成的图案。", "扫描器会读取条形码。", "它帮助商店找到商品和价格。"],
    descriptionKeywords: [{ word: "pattern", zh: "图案" }, { word: "scanner", zh: "扫描器" }, { word: "product", zh: "商品" }],
    discovery: "Different patterns stand for different product numbers.", discoveryZh: "不同的黑白图案代表不同的商品编号。",
    soundTip: "Join two clear words: BAR + code.", soundTipZh: "把两个词清楚连起来：BAR + code。",
    factSourceUrl: "https://www.gs1.org/standards/barcodes",
  }),
  item({
    id: "groceries", sceneId: "supermarket", word: "groceries", wordZh: "食品杂货",
    chunks: [{ id: "gro", text: "gro", cue: "GROH", stressed: true }, { id: "cer", text: "cer", cue: "suh", stressed: false }, { id: "ies", text: "ies", cue: "reez", stressed: false }],
    pronunciation: "GROH · suh · reez", ipa: "/ˈɡroʊsəriz/",
    description: ["Groceries are food and other things we buy for home.", "Fruit, rice and soap can be groceries.", "We put the groceries in bags after paying."],
    descriptionZh: ["groceries 是我们为家里购买的食品和其他用品。", "水果、米和肥皂都可以是 groceries。", "付款后，我们把购买的物品装进袋子。"],
    descriptionKeywords: [{ word: "home", zh: "家" }, { word: "fruit", zh: "水果" }, { word: "bags", zh: "袋子" }],
    discovery: "Groceries can include food, drinks and useful household supplies.", discoveryZh: "groceries 可以包括食物、饮料和常用家庭用品。",
    soundTip: "Keep the middle part very light: GROH-suh-reez.", soundTipZh: "中间的 suh 要读得很轻。",
    factSourceUrl: "https://dictionary.cambridge.org/dictionary/english/groceries",
  }),
  item({
    id: "checkout", sceneId: "supermarket", word: "checkout", wordZh: "结账处 / 结账",
    chunks: [{ id: "check", text: "check", cue: "CHECK", stressed: true }, { id: "out", text: "out", cue: "owt", stressed: false }],
    pronunciation: "CHECK · owt", ipa: "/ˈtʃɛkaʊt/",
    description: ["Checkout is the place where we pay.", "We put our groceries on the counter.", "A cashier or machine scans the items."],
    descriptionZh: ["checkout 是我们付款的地方。", "我们把购买的物品放到柜台上。", "收银员或机器会扫描商品。"],
    descriptionKeywords: [{ word: "pay", zh: "付款" }, { word: "counter", zh: "柜台" }, { word: "scans", zh: "扫描" }],
    discovery: "Checkout can name the place, while check out can describe the action.", discoveryZh: "checkout 可以表示结账处；check out 可以表示结账这个动作。",
    soundTip: "Say CHECK, then open into owt.", soundTipZh: "先读 CHECK，再自然接 owt。",
    factSourceUrl: "https://dictionary.cambridge.org/dictionary/english/checkout",
  }),
  item({
    id: "sunny", sceneId: "weather", word: "sunny", wordZh: "晴朗的",
    chunks: [{ id: "sun", text: "sun", cue: "SUN", stressed: true }, { id: "ny", text: "ny", cue: "ee", stressed: false }],
    pronunciation: "SUN · ee", ipa: "/ˈsʌni/",
    description: ["A sunny day has a lot of bright sunlight.", "The sky may look blue when few clouds cover it.", "We wear a hat to protect our face from the sun."],
    descriptionZh: ["晴天有很多明亮的阳光。", "云很少时，天空可能看起来很蓝。", "我们戴帽子保护脸部，避免暴晒。"],
    descriptionKeywords: [{ word: "sunlight", zh: "阳光" }, { word: "clouds", zh: "云" }, { word: "protect", zh: "保护" }],
    discovery: "Sunlight helps us see and warms Earth's surface.", discoveryZh: "阳光帮助我们看清东西，也会温暖地球表面。",
    soundTip: "Use the short u in sun, then add ee.", soundTipZh: "先读 sun 里的短 u 音，再接 ee。",
    factSourceUrl: "https://www.weather.gov/safety/heat-uv",
  }),
  item({
    id: "cloudy", sceneId: "weather", word: "cloudy", wordZh: "多云的",
    chunks: [{ id: "cloud", text: "cloud", cue: "KLOWD", stressed: true }, { id: "y", text: "y", cue: "ee", stressed: false }],
    pronunciation: "KLOWD · ee", ipa: "/ˈklaʊdi/",
    description: ["A cloudy sky has many clouds.", "Clouds are made of tiny water drops or ice crystals.", "Thick clouds can block some sunlight."],
    descriptionZh: ["多云的天空里有很多云。", "云由微小的水滴或冰晶组成。", "厚云会挡住一部分阳光。"],
    descriptionKeywords: [{ word: "clouds", zh: "云" }, { word: "water drops", zh: "水滴" }, { word: "sunlight", zh: "阳光" }],
    discovery: "A cloud may look solid, but it is a huge group of tiny drops or ice crystals.", discoveryZh: "云看起来像一大块，其实由无数微小水滴或冰晶组成。",
    soundTip: "Let cloud rhyme with loud, then add ee.", soundTipZh: "cloud 和 loud 押韵，然后加 ee。",
    factSourceUrl: "https://scijinks.gov/clouds/",
  }),
  item({
    id: "windy", sceneId: "weather", word: "windy", wordZh: "有风的",
    chunks: [{ id: "wind", text: "wind", cue: "WIN", stressed: true }, { id: "y", text: "y", cue: "dee", stressed: false }],
    pronunciation: "WIN · dee", ipa: "/ˈwɪndi/",
    description: ["A windy day has moving air we can feel.", "Wind can make leaves and flags flutter.", "Strong wind can move branches, so we stay safe."],
    descriptionZh: ["有风的日子里，我们能感到空气在流动。", "风会让树叶和旗子飘动。", "强风会摇动树枝，所以我们要注意安全。"],
    descriptionKeywords: [{ word: "air", zh: "空气" }, { word: "flutter", zh: "飘动" }, { word: "branches", zh: "树枝" }],
    discovery: "Wind is air moving from one place to another.", discoveryZh: "风就是从一个地方流向另一个地方的空气。",
    soundTip: "In windy, wind sounds like WIN, not the verb wind a toy.", soundTipZh: "windy 里的 wind 读 WIN，不是“给玩具上发条”时的读音。",
    factSourceUrl: "https://scijinks.gov/wind/",
  }),
  item({
    id: "rainy", sceneId: "weather", word: "rainy", wordZh: "下雨的",
    chunks: [{ id: "rain", text: "rain", cue: "RAYN", stressed: true }, { id: "y", text: "y", cue: "ee", stressed: false }],
    pronunciation: "RAYN · ee", ipa: "/ˈreɪni/",
    description: ["Rainy weather brings water drops from clouds.", "We use an umbrella or raincoat to stay dry.", "Rain gives water to plants and rivers."],
    descriptionZh: ["雨天时，水滴从云里落下。", "我们用雨伞或雨衣保持干爽。", "雨给植物和河流带来水。"],
    descriptionKeywords: [{ word: "clouds", zh: "云" }, { word: "umbrella", zh: "雨伞" }, { word: "plants", zh: "植物" }],
    discovery: "Rain is part of the water cycle that moves water around Earth.", discoveryZh: "雨是水循环的一部分，它让水在地球上不断移动。",
    soundTip: "Say rain, then add a light ee.", soundTipZh: "先读 rain，再轻轻加 ee。",
    factSourceUrl: "https://www.noaa.gov/education/resource-collections/freshwater/water-cycle",
  }),
  item({
    id: "thunderstorm", sceneId: "weather", word: "thunderstorm", wordZh: "雷暴",
    chunks: [{ id: "thun", text: "thun", cue: "THUN", stressed: true }, { id: "der", text: "der", cue: "duhr", stressed: false }, { id: "storm", text: "storm", cue: "storm", stressed: false }],
    pronunciation: "THUN · duhr · storm", ipa: "/ˈθʌndərstɔrm/",
    description: ["A thunderstorm has thunder, lightning and often heavy rain.", "Thunder is the sound made when lightning heats the air.", "We go indoors and stay away from windows."],
    descriptionZh: ["雷暴会带来雷声、闪电，而且常有大雨。", "闪电使空气迅速变热，从而产生雷声。", "我们要进入室内，并远离窗户。"],
    descriptionKeywords: [{ word: "lightning", zh: "闪电" }, { word: "sound", zh: "声音" }, { word: "indoors", zh: "室内" }],
    discovery: "If you can hear thunder, you are close enough to lightning to go indoors.", discoveryZh: "只要听到雷声，就说明闪电足够近，应该进入室内。",
    soundTip: "Put your tongue gently between your teeth for the th in THUN.", soundTipZh: "读 THUN 开头的 th 时，舌尖轻轻放在上下齿之间。",
    factSourceUrl: "https://www.weather.gov/safety/thunderstorm",
  }),
  item({
    id: "lightning", sceneId: "weather", word: "lightning", wordZh: "闪电",
    chunks: [{ id: "light", text: "light", cue: "LYTE", stressed: true }, { id: "ning", text: "ning", cue: "ning", stressed: false }],
    pronunciation: "LYTE · ning", ipa: "/ˈlaɪtnɪŋ/",
    description: ["Lightning is a giant spark of electricity in the sky.", "It can heat the nearby air very quickly.", "During lightning, we stay safely indoors."],
    descriptionZh: ["闪电是天空中巨大的电火花。", "它能非常快地加热附近空气。", "闪电时，我们应安全地留在室内。"],
    descriptionKeywords: [{ word: "electricity", zh: "电" }, { word: "air", zh: "空气" }, { word: "indoors", zh: "室内" }],
    discovery: "The fast-heated air expands and makes the sound we call thunder.", discoveryZh: "被瞬间加热的空气迅速膨胀，发出我们所说的雷声。",
    soundTip: "Say light, then ning; do not add an extra syllable.", soundTipZh: "先读 light，再接 ning，不要多加一个音节。",
    factSourceUrl: "https://scijinks.gov/lightning/",
  }),
  item({
    id: "temperature", sceneId: "weather", word: "temperature", wordZh: "温度",
    chunks: [{ id: "tem", text: "tem", cue: "TEM", stressed: true }, { id: "pera", text: "pera", cue: "pruh", stressed: false }, { id: "ture", text: "ture", cue: "chuhr", stressed: false }],
    pronunciation: "TEM · pruh · chuhr", ipa: "/ˈtɛmprətʃər/",
    description: ["Temperature tells us how hot or cold something is.", "A thermometer measures temperature.", "Weather reports may show degrees Celsius."],
    descriptionZh: ["温度告诉我们某物有多热或多冷。", "温度计用来测量温度。", "天气报告可能用摄氏度显示温度。"],
    descriptionKeywords: [{ word: "hot or cold", zh: "热或冷" }, { word: "thermometer", zh: "温度计" }, { word: "Celsius", zh: "摄氏" }],
    discovery: "Singapore weather forecasts normally report temperature in degrees Celsius.", discoveryZh: "新加坡的天气预报通常用摄氏度表示温度。",
    soundTip: "In natural speech, the middle becomes quick: TEM-pruh-chuhr.", soundTipZh: "自然语速中间会变快：TEM-pruh-chuhr。",
    factSourceUrl: "https://www.weather.gov/jetstream/temperature",
  }),
  item({
    id: "forecast", sceneId: "weather", word: "forecast", wordZh: "天气预报 / 预测",
    chunks: [{ id: "fore", text: "fore", cue: "FOR", stressed: true }, { id: "cast", text: "cast", cue: "kast", stressed: false }],
    pronunciation: "FOR · kast", ipa: "/ˈfɔrkæst/",
    description: ["A weather forecast tells what the weather may be like.", "Forecasters study clouds, wind and temperature.", "We check the forecast before planning outdoor activities."],
    descriptionZh: ["天气预报告诉我们天气可能会怎样。", "预报员研究云、风和温度。", "安排户外活动前，我们会查看天气预报。"],
    descriptionKeywords: [{ word: "weather", zh: "天气" }, { word: "temperature", zh: "温度" }, { word: "outdoor", zh: "户外的" }],
    discovery: "A forecast is a scientific prediction and can change when new observations arrive.", discoveryZh: "天气预报是科学预测；新观测数据到来后，它也可能改变。",
    soundTip: "Join two familiar parts: FOR + cast.", soundTipZh: "把两部分连起来：FOR + cast。",
    factSourceUrl: "https://www.noaa.gov/education/resource-collections/weather-atmosphere/weather-forecasting",
  }),
];
