export type VocabularyWord = {
  id: string;
  word: string;
  meaning: string;
  meaningZh: string;
  soundParts: string[];
  example: string;
  pageIndex: number;
  icon: string;
  pronunciationHint?: string;
};

export const WORDS_PER_BOOK = 5;

export const WORD_SETS: Record<string, VocabularyWord[]> = {
  "dan-the-flying-man": [
    {
      id: "man",
      word: "man",
      meaning: "a grown-up male person",
      meaningZh: "男人",
      soundParts: ["m", "an"],
      example: "I am Dan, the flying man.",
      pageIndex: 1,
      icon: "🧑",
    },
    {
      id: "can",
      word: "can",
      meaning: "to be able to do something",
      meaningZh: "能够",
      soundParts: ["c", "an"],
      example: "Catch me if you can.",
      pageIndex: 1,
      icon: "💪",
    },
    {
      id: "over",
      word: "over",
      meaning: "above and across something",
      meaningZh: "越过；在上方",
      soundParts: ["o", "ver"],
      example: "Over a house and over a crane.",
      pageIndex: 2,
      icon: "🌈",
    },
    {
      id: "train",
      word: "train",
      meaning: "a long vehicle that runs on tracks",
      meaningZh: "火车",
      soundParts: ["tr", "ai", "n"],
      example: "Over a bridge and over a train.",
      pageIndex: 3,
      icon: "🚆",
    },
    {
      id: "trees",
      word: "trees",
      meaning: "tall plants with trunks and branches",
      meaningZh: "树（复数）",
      soundParts: ["tr", "ee", "s"],
      example: "Over flowers, over trees.",
      pageIndex: 4,
      icon: "🌳",
    },
  ],
  "mrs-wishy-washy": [
    {
      id: "cow",
      word: "cow",
      meaning: "a large farm animal that gives milk",
      meaningZh: "奶牛",
      soundParts: ["c", "ow"],
      example: "Oh, lovely mud, said the cow.",
      pageIndex: 0,
      icon: "🐄",
    },
    {
      id: "pig",
      word: "pig",
      meaning: "a pink farm animal",
      meaningZh: "猪",
      soundParts: ["p", "i", "g"],
      example: "Oh, lovely mud, said the pig.",
      pageIndex: 1,
      icon: "🐷",
    },
    {
      id: "duck",
      word: "duck",
      meaning: "a bird that swims and says quack",
      meaningZh: "鸭子",
      soundParts: ["d", "u", "ck"],
      example: "Oh, lovely mud, said the duck.",
      pageIndex: 2,
      icon: "🦆",
    },
    {
      id: "mud",
      word: "mud",
      meaning: "wet, soft earth",
      meaningZh: "泥巴",
      soundParts: ["m", "u", "d"],
      example: "Oh, lovely mud!",
      pageIndex: 0,
      icon: "🟤",
    },
    {
      id: "rolled",
      word: "rolled",
      meaning: "turned over and over",
      meaningZh: "打滚了",
      soundParts: ["r", "oll", "ed"],
      example: "He rolled in it.",
      pageIndex: 2,
      icon: "🌀",
    },
  ],
  "walking-through-jungle": [
    {
      id: "jungle",
      word: "jungle",
      meaning: "a hot, thick forest",
      meaningZh: "丛林",
      soundParts: ["jun", "gle"],
      example: "Walking through the jungle.",
      pageIndex: 0,
      icon: "🌴",
    },
    {
      id: "lion",
      word: "lion",
      meaning: "a big wild cat with a loud roar",
      meaningZh: "狮子",
      soundParts: ["li", "on"],
      example: "I think I see a lion.",
      pageIndex: 1,
      icon: "🦁",
    },
    {
      id: "whale",
      word: "whale",
      meaning: "a very large animal that lives in the sea",
      meaningZh: "鲸鱼",
      soundParts: ["wh", "ale"],
      example: "I think I see a whale.",
      pageIndex: 3,
      icon: "🐋",
    },
    {
      id: "ocean",
      word: "ocean",
      meaning: "a huge area of salt water",
      meaningZh: "海洋",
      soundParts: ["o", "cean"],
      example: "Floating on the ocean.",
      pageIndex: 2,
      icon: "🌊",
    },
    {
      id: "snake",
      word: "snake",
      meaning: "a long animal with no legs",
      meaningZh: "蛇",
      soundParts: ["sn", "ake"],
      example: "I think I see a snake.",
      pageIndex: 9,
      icon: "🐍",
    },
  ],
  "to-town": [
    {
      id: "town",
      word: "town",
      meaning: "a place where people live and work",
      meaningZh: "城镇",
      soundParts: ["t", "ow", "n"],
      example: "I will go to town.",
      pageIndex: 1,
      icon: "🏘️",
    },
    {
      id: "yellow",
      word: "yellow",
      meaning: "the colour of sunshine",
      meaningZh: "黄色",
      soundParts: ["yel", "low"],
      example: "My big yellow bulldozer.",
      pageIndex: 1,
      icon: "🟡",
    },
    {
      id: "red",
      word: "red",
      meaning: "the colour of a ripe tomato",
      meaningZh: "红色",
      soundParts: ["r", "e", "d"],
      example: "My big red fire-engine.",
      pageIndex: 2,
      icon: "🔴",
    },
    {
      id: "green",
      word: "green",
      meaning: "the colour of fresh leaves",
      meaningZh: "绿色",
      soundParts: ["gr", "ee", "n"],
      example: "My big green vintage car.",
      pageIndex: 3,
      icon: "🟢",
    },
    {
      id: "bike",
      word: "bike",
      meaning: "a vehicle with two wheels",
      meaningZh: "自行车；摩托车",
      soundParts: ["b", "ike"],
      example: "I will go to town on my motor bike.",
      pageIndex: 5,
      icon: "🏍️",
    },
  ],
  "the-hungry-giant": [
    {
      id: "giant",
      word: "giant",
      meaning: "a make-believe person who is very big",
      meaningZh: "巨人",
      soundParts: ["gi", "ant"],
      example: "The Hungry Giant.",
      pageIndex: 0,
      icon: "🧌",
    },
    {
      id: "bread",
      word: "bread",
      meaning: "food baked from flour and water",
      meaningZh: "面包",
      soundParts: ["br", "ea", "d"],
      example: "I want some bread!",
      pageIndex: 1,
      icon: "🍞",
    },
    {
      id: "butter",
      word: "butter",
      meaning: "a soft yellow food made from milk",
      meaningZh: "黄油",
      soundParts: ["but", "ter"],
      example: "I want some butter!",
      pageIndex: 2,
      icon: "🧈",
    },
    {
      id: "honey",
      word: "honey",
      meaning: "sweet food made by bees",
      meaningZh: "蜂蜜",
      soundParts: ["hon", "ey"],
      example: "I want some honey!",
      pageIndex: 3,
      icon: "🍯",
    },
    {
      id: "beehive",
      word: "beehive",
      meaning: "the home where bees live",
      meaningZh: "蜂巢",
      soundParts: ["bee", "hive"],
      example: "The people found a beehive.",
      pageIndex: 6,
      icon: "🐝",
    },
  ],
  "ants-in-a-hurry": [
    {
      id: "ants",
      word: "ants",
      meaning: "tiny insects that live together",
      meaningZh: "蚂蚁（复数）",
      soundParts: ["a", "n", "t", "s"],
      example: "The ants scurry, scurry, scurry.",
      pageIndex: 0,
      icon: "🐜",
    },
    {
      id: "hurry",
      word: "hurry",
      meaning: "to move or do something quickly",
      meaningZh: "赶快",
      soundParts: ["hur", "ry"],
      example: "Hurry, hurry, hurry!",
      pageIndex: 1,
      icon: "💨",
    },
    {
      id: "queen",
      word: "queen",
      meaning: "a woman ruler; the mother ant here",
      meaningZh: "女王；蚁后",
      soundParts: ["qu", "ee", "n"],
      example: "The Queen is hungry.",
      pageIndex: 1,
      icon: "👑",
    },
    {
      id: "jelly",
      word: "jelly",
      meaning: "a soft, wobbly sweet food",
      meaningZh: "果冻",
      soundParts: ["jel", "ly"],
      example: "The Queen wants her jelly.",
      pageIndex: 1,
      icon: "🍮",
    },
    {
      id: "hungry",
      word: "hungry",
      meaning: "wanting or needing food",
      meaningZh: "饥饿的",
      soundParts: ["hun", "gry"],
      example: "More and more baby ants are hungry!",
      pageIndex: 7,
      icon: "😋",
    },
  ],
  "dans-lost-hat": [
    {
      id: "lost",
      word: "lost",
      meaning: "not able to be found",
      meaningZh: "丢失的",
      soundParts: ["l", "o", "st"],
      example: "Dan has lost his flying hat.",
      pageIndex: 1,
      icon: "🔎",
    },
    {
      id: "hat",
      word: "hat",
      meaning: "something worn on the head",
      meaningZh: "帽子",
      soundParts: ["h", "at"],
      example: "He can't find his flying hat.",
      pageIndex: 2,
      icon: "🎩",
    },
    {
      id: "under",
      word: "under",
      meaning: "below something",
      meaningZh: "在……下面",
      soundParts: ["un", "der"],
      example: "He looks under the bed.",
      pageIndex: 1,
      icon: "⬇️",
    },
    {
      id: "cat",
      word: "cat",
      meaning: "a small furry pet that says meow",
      meaningZh: "猫",
      soundParts: ["c", "at"],
      example: "It's a large and fluffy tabby cat.",
      pageIndex: 5,
      icon: "🐈",
    },
    {
      id: "fish",
      word: "fish",
      meaning: "an animal that swims in water",
      meaningZh: "鱼",
      soundParts: ["f", "i", "sh"],
      example: "He puts some fish in a cat food dish.",
      pageIndex: 7,
      icon: "🐟",
    },
  ],
  "baby-sister-came-home": [
    {
      id: "baby",
      word: "baby",
      meaning: "a very young child",
      meaningZh: "婴儿",
      soundParts: ["ba", "by"],
      example: "My baby sister came home.",
      pageIndex: 0,
      icon: "👶",
    },
    {
      id: "sister",
      word: "sister",
      meaning: "a girl who has the same parent as you",
      meaningZh: "姐妹",
      soundParts: ["sis", "ter"],
      example: "My baby sister cried.",
      pageIndex: 1,
      icon: "👧",
    },
    {
      id: "cried",
      word: "cried",
      meaning: "made tears and a sad sound",
      meaningZh: "哭了",
      soundParts: ["cr", "ied"],
      example: "My baby sister cried.",
      pageIndex: 1,
      icon: "😢",
    },
    {
      id: "father",
      word: "father",
      meaning: "a male parent",
      meaningZh: "父亲",
      soundParts: ["fa", "ther"],
      example: "Father carried her.",
      pageIndex: 2,
      icon: "👨",
    },
    {
      id: "brother",
      word: "brother",
      meaning: "a boy who has the same parent as you",
      meaningZh: "兄弟",
      soundParts: ["bro", "ther"],
      example: "Your brother didn't cry when he came home.",
      pageIndex: 5,
      icon: "👦",
    },
  ],
  "mid-autumn-festival": [
    {
      id: "lantern",
      word: "lantern",
      meaning: "a light inside a case that you can carry",
      meaningZh: "灯笼",
      soundParts: ["lan", "tern"],
      example: "I want a tiger lantern.",
      pageIndex: 1,
      icon: "🏮",
    },
    {
      id: "tiger",
      word: "tiger",
      meaning: "a large striped wild cat",
      meaningZh: "老虎",
      soundParts: ["ti", "ger"],
      example: "May I have that tiger lantern?",
      pageIndex: 1,
      icon: "🐯",
    },
    {
      id: "rabbit",
      word: "rabbit",
      meaning: "a small animal with long ears",
      meaningZh: "兔子",
      soundParts: ["rab", "bit"],
      example: "Lee Ling held her rabbit lantern.",
      pageIndex: 2,
      icon: "🐇",
    },
    {
      id: "mooncake",
      word: "mooncake",
      meaning: "a round cake eaten at Mid-Autumn Festival",
      meaningZh: "月饼",
      soundParts: ["moon", "cake"],
      example: "We stopped at the mooncake stall.",
      pageIndex: 3,
      icon: "🥮",
    },
    {
      id: "behind",
      word: "behind",
      meaning: "at the back of something",
      meaningZh: "在……后面",
      soundParts: ["be", "hind"],
      example: "Behind the stall was Lee Ling.",
      pageIndex: 7,
      icon: "↩️",
    },
  ],
  "first-day-hari-raya": [
    {
      id: "baju",
      word: "baju",
      meaning: "a Malay word for clothing",
      meaningZh: "马来语：衣服",
      soundParts: ["ba", "ju"],
      example: "Look at my baju kurung!",
      pageIndex: 3,
      icon: "👚",
      pronunciationHint: "BAH-joo",
    },
    {
      id: "kurung",
      word: "kurung",
      meaning: "part of a traditional Malay outfit",
      meaningZh: "马来传统服装",
      soundParts: ["ku", "rung"],
      example: "My baju kurung is green.",
      pageIndex: 3,
      icon: "🧵",
      pronunciationHint: "koo-ROONG",
    },
    {
      id: "green",
      word: "green",
      meaning: "the colour of fresh leaves",
      meaningZh: "绿色",
      soundParts: ["gr", "ee", "n"],
      example: "My baju kurung is green.",
      pageIndex: 3,
      icon: "🟢",
    },
    {
      id: "visit",
      word: "visit",
      meaning: "to go and spend time with someone",
      meaningZh: "拜访",
      soundParts: ["vis", "it"],
      example: "We are going to visit Grandpa and Grandma.",
      pageIndex: 2,
      icon: "🚪",
    },
    {
      id: "family",
      word: "family",
      meaning: "people who are related and care for one another",
      meaningZh: "家人；家庭",
      soundParts: ["fam", "i", "ly"],
      example: "All the family members are at the house.",
      pageIndex: 6,
      icon: "👨‍👩‍👧‍👦",
    },
  ],
  "lazy-duck": [
    {
      id: "waddled",
      word: "waddled",
      meaning: "walked with short steps from side to side",
      meaningZh: "摇摇摆摆地走",
      soundParts: ["w", "add", "led"],
      example: "Lazy Duck waddled around the farmyard.",
      pageIndex: 1,
      icon: "🦆",
    },
    {
      id: "farmyard",
      word: "farmyard",
      meaning: "the open area beside farm buildings",
      meaningZh: "农场院子",
      soundParts: ["farm", "yard"],
      example: "Lazy Duck waddled around the farmyard.",
      pageIndex: 1,
      icon: "🚜",
    },
    {
      id: "prowled",
      word: "prowled",
      meaning: "moved around quietly while looking for something",
      meaningZh: "悄悄地四处走动",
      soundParts: ["pr", "owl", "ed"],
      example: "She prowled up and down looking for mice.",
      pageIndex: 2,
      icon: "🐈",
    },
    {
      id: "scratched",
      word: "scratched",
      meaning: "scraped a surface with claws or something sharp",
      meaningZh: "抓挖了",
      soundParts: ["scr", "atch", "ed"],
      example: "They scratched and scraped.",
      pageIndex: 3,
      icon: "🐔",
    },
    {
      id: "busiest",
      word: "busiest",
      meaning: "doing more work than everyone else",
      meaningZh: "最忙碌的",
      soundParts: ["bus", "i", "est"],
      example: "I'm the busiest duck you've seen.",
      pageIndex: 10,
      icon: "🧹",
    },
  ],
  "mr-gumpys-outing": [
    {
      id: "river",
      word: "river",
      meaning: "a large natural stream of water",
      meaningZh: "河流",
      soundParts: ["riv", "er"],
      example: "His house was by a river.",
      pageIndex: 1,
      icon: "🌊",
    },
    {
      id: "squabble",
      word: "squabble",
      meaning: "to argue noisily about a small thing",
      meaningZh: "争吵",
      soundParts: ["squ", "ab", "ble"],
      example: "If you don't squabble.",
      pageIndex: 2,
      icon: "🗣️",
    },
    {
      id: "bleating",
      word: "bleating",
      meaning: "making the sound of a sheep or goat",
      meaningZh: "咩咩叫",
      soundParts: ["bl", "eat", "ing"],
      example: "Don't keep bleating.",
      pageIndex: 7,
      icon: "🐑",
    },
    {
      id: "trample",
      word: "trample",
      meaning: "to step heavily on things",
      meaningZh: "踩踏",
      soundParts: ["tr", "am", "ple"],
      example: "If you don't trample about.",
      pageIndex: 9,
      icon: "🐂",
    },
    {
      id: "tipped",
      word: "tipped",
      meaning: "leaned too far to one side",
      meaningZh: "倾斜了",
      soundParts: ["t", "ipp", "ed"],
      example: "The boat tipped.",
      pageIndex: 11,
      icon: "🚣",
    },
  ],
  "a-day-in-the-kitchen-with-grandma": [
    {
      id: "dough",
      word: "dough",
      meaning: "a soft mixture used to make bread or noodles",
      meaningZh: "面团",
      soundParts: ["d", "ough"],
      example: "Grandma mixes the flour, water and salt to make dough.",
      pageIndex: 1,
      icon: "🫓",
    },
    {
      id: "dumplings",
      word: "dumplings",
      meaning: "small pieces of filled or shaped dough or rice food",
      meaningZh: "粽子；饺子类食物",
      soundParts: ["dump", "lings"],
      example: "Let's make rice dumplings!",
      pageIndex: 3,
      icon: "🥟",
    },
    {
      id: "bamboo",
      word: "bamboo",
      meaning: "a tall plant with hard hollow stems",
      meaningZh: "竹子",
      soundParts: ["bam", "boo"],
      example: "Some bamboo leaves on the table.",
      pageIndex: 3,
      icon: "🎋",
    },
    {
      id: "soaked",
      word: "soaked",
      meaning: "left something in liquid until it became very wet",
      meaningZh: "浸泡了",
      soundParts: ["s", "oak", "ed"],
      example: "I soaked some rice in the blue water.",
      pageIndex: 4,
      icon: "💧",
    },
    {
      id: "noodles",
      word: "noodles",
      meaning: "long thin strips of food made from dough",
      meaningZh: "面条",
      soundParts: ["noo", "dles"],
      example: "We start to make noodles.",
      pageIndex: 8,
      icon: "🍜",
    },
  ],
  "life-in-a-shell": [
    {
      id: "protect",
      word: "protect",
      meaning: "to keep someone or something safe",
      meaningZh: "保护",
      soundParts: ["pro", "tect"],
      example: "Their shells protect them.",
      pageIndex: 2,
      icon: "🛡️",
    },
    {
      id: "danger",
      word: "danger",
      meaning: "the chance that something harmful may happen",
      meaningZh: "危险",
      soundParts: ["dan", "ger"],
      example: "When there is danger, a snail pulls its whole body inside its shell.",
      pageIndex: 4,
      icon: "⚠️",
    },
    {
      id: "exoskeleton",
      word: "exoskeleton",
      meaning: "a hard skeleton on the outside of a creature",
      meaningZh: "外骨骼",
      soundParts: ["exo", "skeleton"],
      example: "The shell of a crab or a lobster is called an exoskeleton.",
      pageIndex: 8,
      icon: "🦀",
    },
    {
      id: "hermit",
      word: "hermit",
      meaning: "part of the name for a crab that lives in an empty shell",
      meaningZh: "寄居的",
      soundParts: ["her", "mit"],
      example: "A hermit crab does not have a shell on its body.",
      pageIndex: 10,
      icon: "🐚",
    },
    {
      id: "tide",
      word: "tide",
      meaning: "the regular rise and fall of the sea",
      meaningZh: "潮汐",
      soundParts: ["t", "ide"],
      example: "This happens when the tide comes in.",
      pageIndex: 14,
      icon: "🌊",
    },
  ],
  "the-growl": [
    {
      id: "rumble",
      word: "rumble",
      meaning: "a low, deep continuous sound",
      meaningZh: "低沉的隆隆声",
      soundParts: ["rum", "ble"],
      example: "I heard a little rumble.",
      pageIndex: 1,
      icon: "🌩️",
    },
    {
      id: "classroom",
      word: "classroom",
      meaning: "a room where a class learns",
      meaningZh: "教室",
      soundParts: ["class", "room"],
      example: "I looked around the classroom.",
      pageIndex: 1,
      icon: "🏫",
    },
    {
      id: "grizzly",
      word: "grizzly",
      meaning: "a large brown bear",
      meaningZh: "灰熊",
      soundParts: ["grizz", "ly"],
      example: "Was it coming from a grizzly bear?",
      pageIndex: 4,
      icon: "🐻",
    },
    {
      id: "hungry",
      word: "hungry",
      meaning: "needing or wanting food",
      meaningZh: "饥饿的",
      soundParts: ["hun", "gry"],
      example: "I am so hungry I could eat a horse!",
      pageIndex: 5,
      icon: "🍽️",
    },
    {
      id: "lunch",
      word: "lunch",
      meaning: "the meal eaten around the middle of the day",
      meaningZh: "午餐",
      soundParts: ["l", "unch"],
      example: "Please go and eat your lunch.",
      pageIndex: 7,
      icon: "🍱",
    },
  ],
  "magnetic-max": [
    {
      id: "keys",
      word: "keys",
      meaning: "small metal tools used to open locks",
      meaningZh: "钥匙",
      soundParts: ["k", "ey", "s"],
      example: "The keys went flying into the tree.",
      pageIndex: 4,
      icon: "🔑",
    },
    {
      id: "bolts",
      word: "bolts",
      meaning: "metal fasteners used to hold parts together",
      meaningZh: "螺栓",
      soundParts: ["b", "olt", "s"],
      example: "The iron bolts on his skateboard came out.",
      pageIndex: 6,
      icon: "🔩",
    },
    {
      id: "branches",
      word: "branches",
      meaning: "the parts of a tree that grow out from its trunk",
      meaningZh: "树枝",
      soundParts: ["branch", "es"],
      example: "Hidden by the branches",
      pageIndex: 7,
      icon: "🌳",
    },
    {
      id: "enormous",
      word: "enormous",
      meaning: "very, very large",
      meaningZh: "巨大的",
      soundParts: ["e", "nor", "mous"],
      example: "Max, holding an enormous magnet.",
      pageIndex: 8,
      icon: "🧲",
    },
    {
      id: "magnetic",
      word: "magnetic",
      meaning: "able to attract iron or steel",
      meaningZh: "有磁性的",
      soundParts: ["mag", "net", "ic"],
      example: "Just call me Magnetic Max.",
      pageIndex: 8,
      icon: "🧲",
    },
  ],
  "the-feast": [
    {
      id: "feast",
      word: "feast",
      meaning: "a large special meal",
      meaningZh: "盛宴",
      soundParts: ["f", "east"],
      example: "Come to my dinosaur feast!",
      pageIndex: 2,
      icon: "🍽️",
    },
    {
      id: "delicious",
      word: "delicious",
      meaning: "tasting or smelling very good",
      meaningZh: "美味的",
      soundParts: ["de", "li", "cious"],
      example: "Tasty cakes and delicious ham!",
      pageIndex: 2,
      icon: "😋",
    },
    {
      id: "furious",
      word: "furious",
      meaning: "extremely angry",
      meaningZh: "非常愤怒的",
      soundParts: ["fu", "ri", "ous"],
      example: "Dragon was furious.",
      pageIndex: 8,
      icon: "🔥",
    },
    {
      id: "invitations",
      word: "invitations",
      meaning: "messages asking people to come to an event",
      meaningZh: "邀请函",
      soundParts: ["in", "vi", "ta", "tions"],
      example: "I will make invitations.",
      pageIndex: 12,
      icon: "💌",
    },
    {
      id: "midnight",
      word: "midnight",
      meaning: "twelve o'clock at night",
      meaningZh: "午夜",
      soundParts: ["mid", "night"],
      example: "Saturday night at midnight.",
      pageIndex: 12,
      icon: "🌙",
    },
  ],
  "willy-and-hugh": [
    {
      id: "lonely",
      word: "lonely",
      meaning: "sad because you do not have anyone with you",
      meaningZh: "孤独的",
      soundParts: ["lone", "ly"],
      example: "Willy was lonely.",
      pageIndex: 1,
      icon: "😔",
    },
    {
      id: "useless",
      word: "useless",
      meaning: "not able to help or do what is needed",
      meaningZh: "没有用的",
      soundParts: ["use", "less"],
      example: "They all said he was useless.",
      pageIndex: 3,
      icon: "🤷",
    },
    {
      id: "amazed",
      word: "amazed",
      meaning: "very surprised",
      meaningZh: "惊讶的",
      soundParts: ["a", "maz", "ed"],
      example: "Willy was amazed.",
      pageIndex: 5,
      icon: "😲",
    },
    {
      id: "bench",
      word: "bench",
      meaning: "a long seat for several people",
      meaningZh: "长椅",
      soundParts: ["b", "ench"],
      example: "They sat down on a bench.",
      pageIndex: 6,
      icon: "🪑",
    },
    {
      id: "terrifying",
      word: "terrifying",
      meaning: "making someone feel very afraid",
      meaningZh: "令人恐惧的",
      soundParts: ["ter", "ri", "fy", "ing"],
      example: "He'd seen a terrifying creature!",
      pageIndex: 10,
      icon: "😱",
    },
  ],
};

export function wordsForBook(bookSlug: string): VocabularyWord[] {
  return WORD_SETS[bookSlug] ?? [];
}

export function wordAudioSource(bookSlug: string, wordId: string): string {
  return `/word-audio/${bookSlug}/${wordId}.mp3`;
}
