export type VocabularyWord = {
  id: string;
  word: string;
  meaning: string;
  meaningZh: string;
  soundParts: string[];
  example: string;
  pageIndex: number;
  icon: string;
  pronunciationHint?: string;
};

export const WORDS_PER_BOOK = 5;

export const WORD_SETS: Record<string, VocabularyWord[]> = {
  "dan-the-flying-man": [
    {
      id: "man",
      word: "man",
      meaning: "a grown-up male person",
      meaningZh: "男人",
      soundParts: ["m", "an"],
      example: "I am Dan, the flying man.",
      pageIndex: 1,
      icon: "🧑",
    },
    {
      id: "can",
      word: "can",
      meaning: "to be able to do something",
      meaningZh: "能够",
      soundParts: ["c", "an"],
      example: "Catch me if you can.",
      pageIndex: 1,
      icon: "💪",
    },
    {
      id: "over",
      word: "over",
      meaning: "above and across something",
      meaningZh: "越过；在上方",
      soundParts: ["o", "ver"],
      example: "Over a house and over a crane.",
      pageIndex: 2,
      icon: "🌈",
    },
    {
      id: "train",
      word: "train",
      meaning: "a long vehicle that runs on tracks",
      meaningZh: "火车",
      soundParts: ["tr", "ai", "n"],
      example: "Over a bridge and over a train.",
      pageIndex: 3,
      icon: "🚆",
    },
    {
      id: "trees",
      word: "trees",
      meaning: "tall plants with trunks and branches",
      meaningZh: "树（复数）",
      soundParts: ["tr", "ee", "s"],
      example: "Over flowers, over trees.",
      pageIndex: 4,
      icon: "🌳",
    },
  ],
  "mrs-wishy-washy": [
    {
      id: "cow",
      word: "cow",
      meaning: "a large farm animal that gives milk",
      meaningZh: "奶牛",
      soundParts: ["c", "ow"],
      example: "Oh, lovely mud, said the cow.",
      pageIndex: 0,
      icon: "🐄",
    },
    {
      id: "pig",
      word: "pig",
      meaning: "a pink farm animal",
      meaningZh: "猪",
      soundParts: ["p", "i", "g"],
      example: "Oh, lovely mud, said the pig.",
      pageIndex: 1,
      icon: "🐷",
    },
    {
      id: "duck",
      word: "duck",
      meaning: "a bird that swims and says quack",
      meaningZh: "鸭子",
      soundParts: ["d", "u", "ck"],
      example: "Oh, lovely mud, said the duck.",
      pageIndex: 2,
      icon: "🦆",
    },
    {
      id: "mud",
      word: "mud",
      meaning: "wet, soft earth",
      meaningZh: "泥巴",
      soundParts: ["m", "u", "d"],
      example: "Oh, lovely mud!",
      pageIndex: 0,
      icon: "🟤",
    },
    {
      id: "rolled",
      word: "rolled",
      meaning: "turned over and over",
      meaningZh: "打滚了",
      soundParts: ["r", "oll", "ed"],
      example: "He rolled in it.",
      pageIndex: 2,
      icon: "🌀",
    },
  ],
  "walking-through-jungle": [
    {
      id: "jungle",
      word: "jungle",
      meaning: "a hot, thick forest",
      meaningZh: "丛林",
      soundParts: ["jun", "gle"],
      example: "Walking through the jungle.",
      pageIndex: 0,
      icon: "🌴",
    },
    {
      id: "lion",
      word: "lion",
      meaning: "a big wild cat with a loud roar",
      meaningZh: "狮子",
      soundParts: ["li", "on"],
      example: "I think I see a lion.",
      pageIndex: 1,
      icon: "🦁",
    },
    {
      id: "whale",
      word: "whale",
      meaning: "a very large animal that lives in the sea",
      meaningZh: "鲸鱼",
      soundParts: ["wh", "ale"],
      example: "I think I see a whale.",
      pageIndex: 3,
      icon: "🐋",
    },
    {
      id: "ocean",
      word: "ocean",
      meaning: "a huge area of salt water",
      meaningZh: "海洋",
      soundParts: ["o", "cean"],
      example: "Floating on the ocean.",
      pageIndex: 2,
      icon: "🌊",
    },
    {
      id: "snake",
      word: "snake",
      meaning: "a long animal with no legs",
      meaningZh: "蛇",
      soundParts: ["sn", "ake"],
      example: "I think I see a snake.",
      pageIndex: 9,
      icon: "🐍",
    },
  ],
  "to-town": [
    {
      id: "town",
      word: "town",
      meaning: "a place where people live and work",
      meaningZh: "城镇",
      soundParts: ["t", "ow", "n"],
      example: "I will go to town.",
      pageIndex: 1,
      icon: "🏘️",
    },
    {
      id: "yellow",
      word: "yellow",
      meaning: "the colour of sunshine",
      meaningZh: "黄色",
      soundParts: ["yel", "low"],
      example: "My big yellow bulldozer.",
      pageIndex: 1,
      icon: "🟡",
    },
    {
      id: "red",
      word: "red",
      meaning: "the colour of a ripe tomato",
      meaningZh: "红色",
      soundParts: ["r", "e", "d"],
      example: "My big red fire-engine.",
      pageIndex: 2,
      icon: "🔴",
    },
    {
      id: "green",
      word: "green",
      meaning: "the colour of fresh leaves",
      meaningZh: "绿色",
      soundParts: ["gr", "ee", "n"],
      example: "My big green vintage car.",
      pageIndex: 3,
      icon: "🟢",
    },
    {
      id: "bike",
      word: "bike",
      meaning: "a vehicle with two wheels",
      meaningZh: "自行车；摩托车",
      soundParts: ["b", "ike"],
      example: "I will go to town on my motor bike.",
      pageIndex: 5,
      icon: "🏍️",
    },
  ],
  "the-hungry-giant": [
    {
      id: "giant",
      word: "giant",
      meaning: "a make-believe person who is very big",
      meaningZh: "巨人",
      soundParts: ["gi", "ant"],
      example: "The Hungry Giant.",
      pageIndex: 0,
      icon: "🧌",
    },
    {
      id: "bread",
      word: "bread",
      meaning: "food baked from flour and water",
      meaningZh: "面包",
      soundParts: ["br", "ea", "d"],
      example: "I want some bread!",
      pageIndex: 1,
      icon: "🍞",
    },
    {
      id: "butter",
      word: "butter",
      meaning: "a soft yellow food made from milk",
      meaningZh: "黄油",
      soundParts: ["but", "ter"],
      example: "I want some butter!",
      pageIndex: 2,
      icon: "🧈",
    },
    {
      id: "honey",
      word: "honey",
      meaning: "sweet food made by bees",
      meaningZh: "蜂蜜",
      soundParts: ["hon", "ey"],
      example: "I want some honey!",
      pageIndex: 3,
      icon: "🍯",
    },
    {
      id: "beehive",
      word: "beehive",
      meaning: "the home where bees live",
      meaningZh: "蜂巢",
      soundParts: ["bee", "hive"],
      example: "The people found a beehive.",
      pageIndex: 6,
      icon: "🐝",
    },
  ],
  "ants-in-a-hurry": [
    {
      id: "ants",
      word: "ants",
      meaning: "tiny insects that live together",
      meaningZh: "蚂蚁（复数）",
      soundParts: ["a", "n", "t", "s"],
      example: "The ants scurry, scurry, scurry.",
      pageIndex: 0,
      icon: "🐜",
    },
    {
      id: "hurry",
      word: "hurry",
      meaning: "to move or do something quickly",
      meaningZh: "赶快",
      soundParts: ["hur", "ry"],
      example: "Hurry, hurry, hurry!",
      pageIndex: 1,
      icon: "💨",
    },
    {
      id: "queen",
      word: "queen",
      meaning: "a woman ruler; the mother ant here",
      meaningZh: "女王；蚁后",
      soundParts: ["qu", "ee", "n"],
      example: "The Queen is hungry.",
      pageIndex: 1,
      icon: "👑",
    },
    {
      id: "jelly",
      word: "jelly",
      meaning: "a soft, wobbly sweet food",
      meaningZh: "果冻",
      soundParts: ["jel", "ly"],
      example: "The Queen wants her jelly.",
      pageIndex: 1,
      icon: "🍮",
    },
    {
      id: "hungry",
      word: "hungry",
      meaning: "wanting or needing food",
      meaningZh: "饥饿的",
      soundParts: ["hun", "gry"],
      example: "More and more baby ants are hungry!",
      pageIndex: 7,
      icon: "😋",
    },
  ],
  "dans-lost-hat": [
    {
      id: "lost",
      word: "lost",
      meaning: "not able to be found",
      meaningZh: "丢失的",
      soundParts: ["l", "o", "st"],
      example: "Dan has lost his flying hat.",
      pageIndex: 1,
      icon: "🔎",
    },
    {
      id: "hat",
      word: "hat",
      meaning: "something worn on the head",
      meaningZh: "帽子",
      soundParts: ["h", "at"],
      example: "He can't find his flying hat.",
      pageIndex: 2,
      icon: "🎩",
    },
    {
      id: "under",
      word: "under",
      meaning: "below something",
      meaningZh: "在……下面",
      soundParts: ["un", "der"],
      example: "He looks under the bed.",
      pageIndex: 1,
      icon: "⬇️",
    },
    {
      id: "cat",
      word: "cat",
      meaning: "a small furry pet that says meow",
      meaningZh: "猫",
      soundParts: ["c", "at"],
      example: "It's a large and fluffy tabby cat.",
      pageIndex: 5,
      icon: "🐈",
    },
    {
      id: "fish",
      word: "fish",
      meaning: "an animal that swims in water",
      meaningZh: "鱼",
      soundParts: ["f", "i", "sh"],
      example: "He puts some fish in a cat food dish.",
      pageIndex: 7,
      icon: "🐟",
    },
  ],
  "baby-sister-came-home": [
    {
      id: "baby",
      word: "baby",
      meaning: "a very young child",
      meaningZh: "婴儿",
      soundParts: ["ba", "by"],
      example: "My baby sister came home.",
      pageIndex: 0,
      icon: "👶",
    },
    {
      id: "sister",
      word: "sister",
      meaning: "a girl who has the same parent as you",
      meaningZh: "姐妹",
      soundParts: ["sis", "ter"],
      example: "My baby sister cried.",
      pageIndex: 1,
      icon: "👧",
    },
    {
      id: "cried",
      word: "cried",
      meaning: "made tears and a sad sound",
      meaningZh: "哭了",
      soundParts: ["cr", "ied"],
      example: "My baby sister cried.",
      pageIndex: 1,
      icon: "😢",
    },
    {
      id: "father",
      word: "father",
      meaning: "a male parent",
      meaningZh: "父亲",
      soundParts: ["fa", "ther"],
      example: "Father carried her.",
      pageIndex: 2,
      icon: "👨",
    },
    {
      id: "brother",
      word: "brother",
      meaning: "a boy who has the same parent as you",
      meaningZh: "兄弟",
      soundParts: ["bro", "ther"],
      example: "Your brother didn't cry when he came home.",
      pageIndex: 5,
      icon: "👦",
    },
  ],
  "mid-autumn-festival": [
    {
      id: "lantern",
      word: "lantern",
      meaning: "a light inside a case that you can carry",
      meaningZh: "灯笼",
      soundParts: ["lan", "tern"],
      example: "I want a tiger lantern.",
      pageIndex: 1,
      icon: "🏮",
    },
    {
      id: "tiger",
      word: "tiger",
      meaning: "a large striped wild cat",
      meaningZh: "老虎",
      soundParts: ["ti", "ger"],
      example: "May I have that tiger lantern?",
      pageIndex: 1,
      icon: "🐯",
    },
    {
      id: "rabbit",
      word: "rabbit",
      meaning: "a small animal with long ears",
      meaningZh: "兔子",
      soundParts: ["rab", "bit"],
      example: "Lee Ling held her rabbit lantern.",
      pageIndex: 2,
      icon: "🐇",
    },
    {
      id: "mooncake",
      word: "mooncake",
      meaning: "a round cake eaten at Mid-Autumn Festival",
      meaningZh: "月饼",
      soundParts: ["moon", "cake"],
      example: "We stopped at the mooncake stall.",
      pageIndex: 3,
      icon: "🥮",
    },
    {
      id: "behind",
      word: "behind",
      meaning: "at the back of something",
      meaningZh: "在……后面",
      soundParts: ["be", "hind"],
      example: "Behind the stall was Lee Ling.",
      pageIndex: 7,
      icon: "↩️",
    },
  ],
  "first-day-hari-raya": [
    {
      id: "baju",
      word: "baju",
      meaning: "a Malay word for clothing",
      meaningZh: "马来语：衣服",
      soundParts: ["ba", "ju"],
      example: "Look at my baju kurung!",
      pageIndex: 3,
      icon: "👚",
      pronunciationHint: "BAH-joo",
    },
    {
      id: "kurung",
      word: "kurung",
      meaning: "part of a traditional Malay outfit",
      meaningZh: "马来传统服装",
      soundParts: ["ku", "rung"],
      example: "My baju kurung is green.",
      pageIndex: 3,
      icon: "🧵",
      pronunciationHint: "koo-ROONG",
    },
    {
      id: "green",
      word: "green",
      meaning: "the colour of fresh leaves",
      meaningZh: "绿色",
      soundParts: ["gr", "ee", "n"],
      example: "My baju kurung is green.",
      pageIndex: 3,
      icon: "🟢",
    },
    {
      id: "visit",
      word: "visit",
      meaning: "to go and spend time with someone",
      meaningZh: "拜访",
      soundParts: ["vis", "it"],
      example: "We are going to visit Grandpa and Grandma.",
      pageIndex: 2,
      icon: "🚪",
    },
    {
      id: "family",
      word: "family",
      meaning: "people who are related and care for one another",
      meaningZh: "家人；家庭",
      soundParts: ["fam", "i", "ly"],
      example: "All the family members are at the house.",
      pageIndex: 6,
      icon: "👨‍👩‍👧‍👦",
    },
  ],
};

export function wordsForBook(bookSlug: string): VocabularyWord[] {
  return WORD_SETS[bookSlug] ?? [];
}

export function wordAudioSource(bookSlug: string, wordId: string): string {
  return `/word-audio/${bookSlug}/${wordId}.mp3`;
}
